/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type AiJobKind = 'ats_cv' | 'interview_feedback' | 'prompt_run' | 'statement_review';

export type CardKind = 'multiple_choice' | 'order_steps' | 'reveal' | 'swipe_binary';

export type CoinEntry =
  | 'adjust'
  | 'earn_lesson'
  | 'earn_review'
  | 'earn_streak'
  | 'hold'
  | 'purchase'
  | 'release'
  | 'settle'
  | 'spend_ai'
  | 'spend_scan'
  | 'spend_store';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LeagueTier = 'bronze' | 'gold' | 'silver';

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = 'mentor' | 'student' | 'superadmin';

export interface AiJobs {
  completed_at: Timestamp | null;
  cost_usd: Numeric | null;
  created_at: Generated<Timestamp>;
  error_message: string | null;
  id: Generated<string>;
  input: Json;
  input_tokens: number | null;
  kind: AiJobKind;
  model: string | null;
  output: Json | null;
  output_tokens: number | null;
  prompt_version: string | null;
  status: Generated<string>;
  user_id: string;
}

export interface AuditLog {
  action: string;
  actor_id: string | null;
  after: Json | null;
  before: Json | null;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  ip: string | null;
  subject_id: string | null;
  subject_type: string | null;
}

export interface AuthAccounts {
  access_token: string | null;
  access_token_expires_at: Timestamp | null;
  account_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  id_token: string | null;
  password: string | null;
  provider_id: string;
  refresh_token: string | null;
  refresh_token_expires_at: Timestamp | null;
  scope: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AuthVerifications {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  identifier: string;
  updated_at: Generated<Timestamp>;
  value: string;
}

export interface CoinLedger {
  amount: number;
  balance_after: number;
  created_at: Generated<Timestamp>;
  entry_type: CoinEntry;
  id: Generated<Int8>;
  idempotency_key: string | null;
  note: string | null;
  ref_id: string | null;
  ref_type: string | null;
  user_id: string;
}

export interface CvDocuments {
  ats_findings: Json | null;
  ats_score: number | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  job_id: string | null;
  pdf_key: string | null;
  structured: Json;
  user_id: string;
}

export interface DailyQuests {
  completed_at: Timestamp | null;
  done_tasks: Generated<number>;
  quest_date: string;
  target_tasks: Generated<number>;
  user_id: string;
}

export interface LeagueSeasons {
  closed_at: Timestamp | null;
  code: string;
  ends_at: Timestamp;
  id: Generated<string>;
  starts_at: Timestamp;
}

export interface LeagueStandings {
  closed_at: Timestamp | null;
  outcome: string | null;
  points: Generated<number>;
  rank: number | null;
  season_id: string;
  squad_id: string;
  tier: LeagueTier;
}

export interface LessonAttempts {
  attempt_date: string;
  card_results: Json;
  coins: number;
  completed_at: Generated<Timestamp>;
  duration_ms: number;
  id: Generated<string>;
  lesson_id: string;
  points: number;
  score: number;
  user_id: string;
}

export interface LessonCards {
  content: Json;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: CardKind;
  lesson_id: string;
  prompt: string;
  sort_order: Generated<number>;
}

export interface Lessons {
  base_coins: Generated<number>;
  base_points: Generated<number>;
  created_at: Generated<Timestamp>;
  est_seconds: Generated<number>;
  id: Generated<string>;
  module_id: string;
  sort_order: Generated<number>;
  title: string;
}

export interface MasterySessions {
  created_at: Generated<Timestamp>;
  feedback: Json | null;
  id: Generated<string>;
  kind: string;
  mentor_id: string | null;
  mentor_note: string | null;
  status: Generated<string>;
  target: string | null;
  turns: Generated<Json>;
  user_id: string;
}

export interface Modules {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  sort_order: Generated<number>;
  title: string;
  track_id: string;
}

export interface Notifications {
  body: string;
  created_at: Generated<Timestamp>;
  data: Json | null;
  id: Generated<string>;
  kind: string;
  read_at: Timestamp | null;
  sent_at: Timestamp | null;
  title: string;
  user_id: string;
}

export interface Orders {
  amount_idr: number;
  coins: number;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  idempotency_key: string;
  paid_at: Timestamp | null;
  pricing_version: number;
  provider: Generated<string>;
  provider_ref: string | null;
  status: Generated<string>;
  user_id: string;
}

export interface OutboxEvents {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  payload: Json;
  processed_at: Timestamp | null;
  topic: string;
}

export interface Payments {
  event_type: string;
  id: Generated<string>;
  order_id: string;
  provider: string;
  raw_payload: Json;
  received_at: Generated<Timestamp>;
  signature_ok: boolean;
}

export interface PeerReviews {
  /**
   * Isu #15. Bagian dari FK majemuk ke lesson_attempts (id, attempt_date). WAJIB diambil dari baris lesson_attempts itu sendiri, TIDAK PERNAH dibentuk di Node: ini tanggal LOKAL pengguna, dan Date milik proses Node akan meleset satu hari untuk sebagian pengguna.
   */
  attempt_date: string;
  attempt_id: string;
  author_id: string;
  comment: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  mentor_checked: Generated<boolean>;
  mentor_delta: number | null;
  reviewer_id: string;
  rubric_scores: Json;
  weighted_points: Generated<number>;
}

export interface PlagiarismScans {
  cached_from: string | null;
  completed_at: Timestamp | null;
  cost_coins: number;
  created_at: Generated<Timestamp>;
  document_key: string;
  document_sha256: string;
  error_message: string | null;
  filename: string;
  hold_ledger_id: Int8 | null;
  id: Generated<string>;
  provider: Generated<string>;
  provider_scan_id: string | null;
  report_key: string | null;
  similarity_score: Numeric | null;
  status: Generated<string>;
  user_id: string;
  word_count: number | null;
}

export interface PricingConfig {
  active_from: Generated<Timestamp>;
  coin_price_idr: number;
  created_by: string | null;
  cv_cost_coins: number;
  freeze_cost_coins: number;
  interview_cost_coins: number;
  lesson_reward_coins: number;
  packages: Json;
  prompt_run_cost_coins: number;
  scan_cached_cost_coins: number;
  scan_cost_coins: number;
  statement_cost_coins: number;
  version: number;
}

export interface PromptRuns {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  job_id: string | null;
  output: string | null;
  self_rating: number | null;
  structure: Json;
  user_id: string;
}

export interface PushTokens {
  auth: string;
  created_at: Generated<Timestamp>;
  endpoint: string;
  id: Generated<string>;
  p256dh: string;
  user_id: string;
}

export interface RefreshTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  replaced_by: string | null;
  revoked_at: Timestamp | null;
  token_hash: string;
  user_agent: string | null;
  user_id: string;
}

export interface ReviewerWeights {
  avg_deviation: Numeric | null;
  samples: Generated<number>;
  updated_at: Generated<Timestamp>;
  user_id: string;
  weight: Generated<Numeric>;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  /**
   * text, bukan inet: Better-Auth meneruskan X-Forwarded-For apa adanya dan rantai proxy bukan inet yang sah.
   */
  ip: string | null;
  token: string;
  updated_at: Generated<Timestamp>;
  user_agent: string | null;
  user_id: string;
}

export interface SquadMembers {
  id: Generated<string>;
  joined_at: Generated<Timestamp>;
  left_at: Timestamp | null;
  squad_id: string;
  user_id: string;
  weekly_points: Generated<number>;
}

export interface Squads {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  league_tier: Generated<LeagueTier>;
  max_members: Generated<number>;
  mentor_id: string | null;
  name: string;
  season_id: string | null;
}

export interface StoreItems {
  asset_key: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  kind: string;
  price_coins: number;
  slug: string;
  title: string;
}

export interface StorePurchases {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  item_id: string;
  ledger_id: Int8 | null;
  price_coins: number;
  user_id: string;
}

export interface Streaks {
  current_streak: Generated<number>;
  freeze_credits: Generated<number>;
  freeze_purchased_month: string | null;
  freeze_used_date: string | null;
  last_activity_date: string | null;
  longest_streak: Generated<number>;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Tracks {
  category: string | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  is_published: Generated<boolean>;
  slug: string;
  sort_order: Generated<number>;
  title: string;
}

export interface Users {
  avatar_url: string | null;
  coin_balance: Generated<number>;
  created_at: Generated<Timestamp>;
  display_name: string;
  email: string;
  /**
   * AU-8: false memblokir top-up. Ditulis Better-Auth. Menggantikan email_verified_at (isu #35 opsi 1) yang dibuang di migrasi contract.
   */
  email_verified: Generated<boolean>;
  email_verified_at: Timestamp | null;
  id: Generated<string>;
  /**
   * USANG sejak 004. Password ada di auth_accounts.password. Dibuang di migrasi contract.
   */
  password_hash: string | null;
  role: Generated<UserRole>;
  status: Generated<string>;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  ai_jobs: AiJobs;
  audit_log: AuditLog;
  auth_accounts: AuthAccounts;
  auth_verifications: AuthVerifications;
  coin_ledger: CoinLedger;
  cv_documents: CvDocuments;
  daily_quests: DailyQuests;
  league_seasons: LeagueSeasons;
  league_standings: LeagueStandings;
  lesson_attempts: LessonAttempts;
  lesson_cards: LessonCards;
  lessons: Lessons;
  mastery_sessions: MasterySessions;
  modules: Modules;
  notifications: Notifications;
  orders: Orders;
  outbox_events: OutboxEvents;
  payments: Payments;
  peer_reviews: PeerReviews;
  plagiarism_scans: PlagiarismScans;
  pricing_config: PricingConfig;
  prompt_runs: PromptRuns;
  push_tokens: PushTokens;
  refresh_tokens: RefreshTokens;
  reviewer_weights: ReviewerWeights;
  sessions: Sessions;
  squad_members: SquadMembers;
  squads: Squads;
  store_items: StoreItems;
  store_purchases: StorePurchases;
  streaks: Streaks;
  tracks: Tracks;
  users: Users;
}
